port: 5555
domain: writeup.com
email: hello@writeup.com
url: http://writeup.com
img_url: http://writeup.com/images
title: Write Up
author: Henrik Vendelbo
description: Web Page Specification for Quality Assurance

exclude: 
- Rakefile
- README
- testing.log
- distribute-0.6.21.tar.gz
- GitHub Write-Up.xcodeproj
- GitHub Write-Up
- www

